apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
      name: backend
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${artifact.image}:${artifact.tag}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POSTGRES_HOST
              value: postgres-release-postgresql.default.svc.cluster.local
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-release-postgresql
                  key: postgresql-password
          envFrom:
            - secretRef:
                name: backend-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80