apiVersion: ENC[AES256_GCM,data:AqU=,iv:mB2boszDnPQiV7DTX4KziT7r/oYqW09+8YIrit8Mcsw=,tag:NryFaw1rys2jKgVjwpnRLg==,type:str]
kind: ENC[AES256_GCM,data:cvIxHLmF,iv:EsI9guEIT/7o4ofTDWTaU0icxuuUPvGcajaNgMXmtZ0=,tag:alANwSAuvh/ZWfmHfM7Dgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wX7QoGGHfilW1SuoMgCg,iv:74NXJsSpGVxltykb0CpBhPerL8//tvZJl8AuJHbIL5E=,tag:yFlJHo/kThRUDS/GnqaDTw==,type:str]
type: ENC[AES256_GCM,data:UzknwLt5,iv:+8TW/Q5VrctdGow9xX3oK13iM/boshw2t3208/d0+bM=,tag:xiQRVHy06ozKgvtPCce+ng==,type:str]
data:
    SECRET_TOKEN: ENC[AES256_GCM,data:N0zG5bkSQy/kpyTTFq4TcYKW+tA=,iv:HprxFJXtxDKZUpWu4ln/MfMMZxd2PiswezPuhZSepGk=,tag:ApV04wZBotZOkpWSL33uUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-08-29T19:56:34Z'
    mac: ENC[AES256_GCM,data:Uy+jAujn3d7e/bzgriSBMZOMnmWyJzCxV2AmizQqe/aySrfcGroyGfx+06gzW0BhEp1jypDnfNj1klzmhtfwFCEChVMZv8b6Tatk7pmZHSm9LM3cyu3wLoKtFf1fQ5UaxeCVnYvHN6TkYq0fEPgEfJx7NicH5rGkP4LMo5LchN8=,iv:w26Pdb31u8Yu5J8hoIQvOgN48Al6AvriM2KCAk0A7X4=,tag:irYx+QFnaXn/wjYdQBm+xQ==,type:str]
    pgp:
    -   created_at: '2021-08-29T19:56:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2sjJv/f1+VOAQv/cm77heffk47duEaje3ITR8tLjHaRLPX5+7oOOV7rgER5
            ZFYcXRx3tRFm7F0cjaQ2NlD1OUgXtpazIdVGF/pIN/IP9nCE/NtvbA7LaHHUSTYI
            tzoWFwIx9MwisC7VrwDjrGYBZb8e2koECNCJbyBdq09W8pD9aP0I4ZC9JHhh/OWv
            OKh75dzONX8nuZ3rUOdL155q7spNaIDtCX6V+JZQSHo7Jh9ckcY+HFAU9635aLaP
            nsmpnwtf6H5svOKvkBonlyiiA27nMxnihXIHC8/+4E081wDmkyF8Xr0dRmXXOpnt
            /WReNyrAJUk80Ea3yzIftpf5sbaqjdxfzJsHf55iOhf0lKx1y42OrJSqZTCHVgbG
            N7OhKNWDO9xqkqCkW5WKkPHU4u6fbnApm2WF8eR6BWnflp3CtL7tiKmdiYv5B8uk
            1IJ3q4LiYTnJQsiqFSH+uz2ibCReidQBEffgOV+nf7iS5qRTfKQSd9j0USKF9d/H
            YJxphOVyfE2r5RxgokKk0lwBby4empO6a0QeO9jxnjt6K+5or0xFlSRSgnO3LWSp
            77xOOOVrxgvv8PDUIuHBSSytlfefTWgYabFFKGJVH5JwpmQsbOm3ygnfKX8RpdEh
            9JD0HtKSSlhItSFjzw==
            =Mr6j
            -----END PGP MESSAGE-----
        fp: 68DD289788F7EA4994C0B969B246F6514637BB96
    unencrypted_suffix: _unencrypted
    version: 3.5.0
